services:
  db:
    image: postgres:17
    container_name: klinika-db
    environment:
      POSTGRES_DB: klinika
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: haslo123
    ports:
      - "5434:5432"
    volumes:
      - dane-klinika:/var/lib/postgresql/data

  app:
    build: .
    container_name: klinika-app
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/klinika
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: haslo123
      JWT_SEKRET: tajnyKluczDoPodpisywaniaTokenowKtoryMusiBycOdpowiednioDlugi123456789
      JWT_WAZNOSCMS: 3600000
    ports:
      - "8080:8080"

volumes:
  dane-klinika: